[package]
name = "surveilrctl"
version = "0.1.4"
edition = "2021"
description = "Setup utilities of surveilr osquery-ms server"

[dependencies]
upt = "0.9.0"
clap = { version = "4.5.32", features = ["derive", "env"] }